apiVersion: v1
kind: ServiceAccount
metadata:
  name: todoapp-role
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todoapp-role-sec-lst
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todoapp-role-bind-sec
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: todoapp-role
    namespace: todoapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: todoapp-role-sec-lst

